export const fakeArtwork = {
    "width": 1280,
    "height": 720,
    "image": "https://res.cloudinary.com/dqmv3pllu/image/upload/v1688481926/artworks/kjwfo9lgfnjtcsts3bc7.png",
    "opacity": 1,
    "totalLayers": 4,
    "mimetype": "Psd",
    "name": "hinhtv3.psd",
    layers: [{
        "width": 864,
        "height": 720,
        "name": "kuuga",
        "type": "image",
        "font": null,
        "image": "https://res.cloudinary.com/dqmv3pllu/image/upload/v1688481945/artworks/h5oeluaplpiyuc4tzka4.png",
        "text": null,
        "x": 569,
        "y": -264,
        "index": 1,
        "opacity": 1,
        "_id": "wqbHao",
        "groupId": 1
    },
    {
        "width": 581,
        "height": 720,
        "name": "Hinhtv",
        "type": "image",
        "font": null,
        "image": "https://res.cloudinary.com/dqmv3pllu/image/upload/v1688481938/artworks/fogxo17jid2qepuq5mbw.png",
        "text": null,
        "x": -43,
        "y": 0,
        "index": 2,
        "opacity": 1,
        "_id": "o5AY5M",
        "groupId": 1
    },
    {
        "width": 578,
        "height": 720,
        "name": "ToonHinhtv",
        "type": "image",
        "font": null,
        "image": "https://res.cloudinary.com/dqmv3pllu/image/upload/v1688481932/artworks/ywcqqqsefusiuocrjx0k.png",
        "text": null,
        "x": 621,
        "y": 99,
        "index": 3,
        "opacity": 1,
        "_id": "DKjEMV"
    },
    {
        "width": 1280,
        "height": 720,
        "name": "Background",
        "type": "image",
        "font": null,
        "image": "https://res.cloudinary.com/dqmv3pllu/image/upload/v1688481928/artworks/iqrd18wyxf7xa03zsb70.png",
        "text": null,
        "x": 0,
        "y": 0,
        "index": 4,
        "opacity": 1,
        "_id": "rBd1Pm"
    }]
}